package perpustakaan.ui;

import java.awt.print.Book;
import java.sql.*;
import javax.swing.JOptionPane;
import perpustakaan.helper.ConnectionHelper;

/**
 *
 * @author fadil
 */
public class AddBookJFrame extends javax.swing.JFrame {
    
    String penerbit = "";
    String formTitle = "";
    Book bukuGlobal;
    int bukuId = 0;

    /**
     * Creates new form AddBookJFrame
     */
    public AddBookJFrame() {
        initComponents();
    }
    
    public AddBookJFrame(String title, int id) {
        initComponents();
        addBookLabel.setText("Update Buku");
        formTitle = title;
        bukuId = id;
        
         try {
            Connection con = ConnectionHelper.getConnection();
            Statement stm = con.createStatement();
            String query = "SELECT * FROM buku";
            ResultSet rs = stm.executeQuery(query);
            
            while(rs.next()){
                bookTitleField.setText(rs.getString("id_buku"));
                bookAuthorField.setText(rs.getString("Pengarang"));
                switch(rs.getString("Penerbit")){
                    case "Jember Pustaka":
                        jbrPustakaRadBtn.setSelected(true);
                        break;
                        case "Gramedia":
                        gramediaRadBtn.setSelected(true);
                        break;
                        case "Polije Press":
                        polijePressRadBtn.setSelected(true);
                        break;
                        case "RRI Library":
                        rriLibRadBtn.setSelected(true);
                        break;
                        default:
                            System.out.println("Tidak Ada Yang Tepilih");
                            break;
                }
            }
        } catch (Exception e) {
            System.out.println("Error:" + e.getMessage());
        }
    }
    
    public void addBook(){
        try {
            Connection con = ConnectionHelper.getConnection();
            Statement stm = con.createStatement();
            
            getPenerbitRadBtn();
            
            String query = "INSERT INTO buku (judul_buku, pengarang, penerbit, tahun_terbit) "
                    + "VALUES ('"+ bookTitleField.getText()+"', '"+ bookAuthorField.getText() +"', '"+ 
                    penerbit +"', '"+ thnTerbitComboBox.getSelectedItem() +"');";
            
            stm.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "SUKSES", "COMPLITE", JOptionPane.INFORMATION_MESSAGE);
            
            AddBookJFrame.this.setVisible(false);
            new ShowBookJFrame().setVisible(true);
            
        } catch (Exception e) {
            System.out.println("Error:" + e.getMessage());
        }
    }
        public void updateBuku(int id){
        try {
            Connection con = ConnectionHelper.getConnection();
            Statement stm = con.createStatement();
            getPenerbitRadBtn();
            
            String query = "UPDATE Buku SET Judul_Buku = "+ bookTitleField.getText() +"', pengarang = '"+ bookAuthorField.getText() +"', "
                    + "penerbit = '"+ penerbit +"', tahun_terbit = '"+ thnTerbitComboBox.getSelectedItem() +"'WHERE id_buku = " + id;
            
            stm.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "DATA BERHASIL DI UPDATE", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
            
            AddBookJFrame.this.setVisible(false);
            new ShowBookJFrame().setVisible(true);
            
        } catch (Exception e) {
            System.out.println("Error:" + e.getMessage());
        }
    }
    void getPenerbitRadBtn(){
        if(jbrPustakaRadBtn.isSelected()){
            penerbit = "Jember Pustaka";
        }else if(gramediaRadBtn.isSelected()){
            penerbit = "Gramedia";
        }else if(polijePressRadBtn.isSelected()){
            penerbit = "Polije Press";
        }else if(rriLibRadBtn.isSelected()){
            penerbit = "RRI Library";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        addBookLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bookTitleField = new javax.swing.JTextField();
        bookAuthorField = new javax.swing.JTextField();
        thnTerbitComboBox = new javax.swing.JComboBox<>();
        simpanBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jbrPustakaRadBtn = new javax.swing.JRadioButton();
        gramediaRadBtn = new javax.swing.JRadioButton();
        polijePressRadBtn = new javax.swing.JRadioButton();
        rriLibRadBtn = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addBookLabel.setText("Tambah Buku");

        jLabel2.setText("Judul");

        jLabel3.setText("Pengarang");

        jLabel4.setText("Penerbit");

        jLabel5.setText("Tahun Terbit");

        thnTerbitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2011", "2012", "2013", "2014", "2015" }));

        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(jbrPustakaRadBtn);
        jbrPustakaRadBtn.setText("Jember Pustaka");

        buttonGroup1.add(gramediaRadBtn);
        gramediaRadBtn.setText("Gramedia");

        buttonGroup1.add(polijePressRadBtn);
        polijePressRadBtn.setText("Polije Press");

        buttonGroup1.add(rriLibRadBtn);
        rriLibRadBtn.setText("RRI Library");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thnTerbitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bookAuthorField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addComponent(bookTitleField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbrPustakaRadBtn)
                                    .addComponent(gramediaRadBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rriLibRadBtn)
                                    .addComponent(polijePressRadBtn)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(addBookLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(simpanBtn)
                        .addGap(44, 44, 44)
                        .addComponent(cancelBtn)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(addBookLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bookTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bookAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jbrPustakaRadBtn)
                    .addComponent(polijePressRadBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gramediaRadBtn)
                    .addComponent(rriLibRadBtn))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thnTerbitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanBtn)
                    .addComponent(cancelBtn))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        if(bukuId == 0){
            addBook();
        }else{
            updateBuku(bukuId);
        }
    }//GEN-LAST:event_simpanBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBookLabel;
    private javax.swing.JTextField bookAuthorField;
    private javax.swing.JTextField bookTitleField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JRadioButton gramediaRadBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jbrPustakaRadBtn;
    private javax.swing.JRadioButton polijePressRadBtn;
    private javax.swing.JRadioButton rriLibRadBtn;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JComboBox<String> thnTerbitComboBox;
    // End of variables declaration//GEN-END:variables
}
